// Colors use CSS variables so they adapt to the active theme (dark/light/rosa)
export const C = {
  amber: 'var(--rz-amber)',
  amberDim: 'var(--rz-amber-dim)',
  amberGlow: 'var(--rz-amber-glow)',
  teal: 'var(--rz-teal)',
  tealDim: 'var(--rz-teal-dim)',
  green: 'var(--rz-green)',
  greenDim: 'var(--rz-green-dim)',
  red: 'var(--rz-red)',
  redDim: 'var(--rz-red-dim)',
  yellow: 'var(--rz-yellow)',
  yellowDim: 'var(--rz-yellow-dim)',
  violet: 'var(--rz-violet)',
  violetDim: 'var(--rz-violet-dim)',
  blue: 'var(--rz-blue)',
  blueDim: 'var(--rz-blue-dim)',
  text: 'var(--rz-text)',
  text2: 'var(--rz-text-2)',
  text3: 'var(--rz-text-3)',
  bg: 'var(--rz-bg)',
  surface: 'var(--rz-surface)',
  surface2: 'var(--rz-surface-2)',
  surface3: 'var(--rz-surface-3)',
  border: 'var(--rz-border)',
  borderMd: 'var(--rz-border-md)',
  card: 'var(--rz-surface)',
  card2: 'var(--rz-surface-2)',
  sub: 'var(--rz-text-2)',
  muted: 'var(--rz-text-3)',
  amber2: 'var(--rz-amber-2)',
  amberBorder: 'rgba(240,168,78,0.25)',
  orange: '#FB923C',
  orangeDim: 'rgba(251,146,60,0.10)',
}
